server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # -- Proxy API calls to the internal API Gateway (ms-01-gateway:3000) --
    location /api/ {
        proxy_pass         http://nexus-ms-01-gateway:3000/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_read_timeout 60s;
    }

    # -- Micro-frontend: web-academic (Module Federation remote) --
    location /academic-mf/ {
        proxy_pass         http://nexus-web-academic:80/academic-mf/;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        add_header         Access-Control-Allow-Origin *;
    }

    # -- Micro-frontend: web-campus (Module Federation remote) --
    location /campus-mf/ {
        proxy_pass         http://nexus-web-campus:80/campus-mf/;
        proxy_http_version 1.1;
        proxy_set_header   Host $host;
        add_header         Access-Control-Allow-Origin *;
    }

    # -- SPA fallback: serve index.html for any unknown paths --
    location / {
        try_files $uri $uri/ /index.html;
    }
}
