# Etapa 1: Construcción (Builder)
FROM golang:alpine AS builder

WORKDIR /app

# Descargamos las dependencias
COPY go.mod go.sum ./
RUN go mod download

# Copiamos el código fuente, incluyendo la carpeta autogenerada 'pb'
COPY . .

# Compilamos el binario y lo llamamos 'booking-engine'
RUN go build -o booking-engine main.go

# Etapa 2: Imagen final ultra ligera
FROM alpine:latest

WORKDIR /app

# Copiamos ÚNICAMENTE el binario ya compilado desde la etapa anterior
COPY --from=builder /app/booking-engine .

# Exponemos el puerto de gRPC
EXPOSE 50051

# Ejecutamos el binario
CMD ["./booking-engine"]