# Usa una imagen ligera de Node.js
FROM node:20-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia primero los archivos de dependencias para aprovechar la caché de Docker
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto que usa el Gateway
EXPOSE 3000

# Comando para iniciar el servicio
CMD ["npx", "ts-node", "src/index.ts"]