# Etapa 1: Compilación de recursos estáticos
FROM public.ecr.aws/docker/library/node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Servidor web de producción Nginx
FROM public.ecr.aws/docker/library/nginx:1.25-alpine
# Habilitar CORS en Nginx para Module Federation
RUN echo 'server { \
    listen 80; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html index.htm; \
        try_files $uri $uri/ /index.html; \
        add_header Access-Control-Allow-Origin *; \
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0"; \
    } \
}' > /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
